webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from webapp.db import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(30), index=True)
    email = db.Column(db.String(50), unique=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role == 'admin'

    def __repr__(self):
        return '<User {}>'.format(self.username)

webapp/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    submit = SubmitField('Submit')

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
from webapp.user.models import User


class LoginForm(FlaskForm):
    username = StringField('Name', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember me', default=True)
    submit = SubmitField('Submit')


class RegistrationForm(FlaskForm):
    username = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Submit')

    def validate_username(self, username):
        user_count = User.query.filter_by(username=username.data).count()
        if user_count > 0:
            raise ValidationError('User with this name already exist')

    def validate_email(self, email):
        user_count = User.query.filter_by(email=email.data).count()
        if user_count > 0:
            raise ValidationError('User with this email already exist')

webapp/__init__.py
from flask import Flask
from flask_login import LoginManager, current_user, login_required
from flask_migrate import Migrate
from webapp.user.views import blueprint as user_blueprint
from webapp.admin.views import blueprint as admin_blueprint
from webapp.site.views import blueprint as site_blueprint
from webapp.db import db
from webapp.user.models import User


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)
    migrate = Migrate(app, db)

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'user.login'

    app.register_blueprint(admin_blueprint)
    app.register_blueprint(site_blueprint)
    app.register_blueprint(user_blueprint)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    return app

webapp/admin/views.py
from flask import Blueprint, render_template
from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@admin_required
def admin_index():
    title = 'Admin Panel'
    return render_template('admin/index.html', page_title=title)

webapp/site/views.py
from flask import Blueprint, render_template

blueprint = Blueprint('site', __name__)


@blueprint.route('/')
def index():
    title = 'Beauty laser treatments and calorie burning bed sessions - to make you feel renewed'
    return render_template('site/index.html', page_title=title)


@blueprint.route('/promotions')
def promotions():
    title = 'Specials and promotions of laser treatment'
    return render_template('site/promotions.html', page_title=title)


@blueprint.route('/contact')
def contact():
    title = 'Contact us to make a booking!'
    return render_template('site/contact.html', page_title=title)


@blueprint.route('/faq')
def faq():
    title = 'Frequently asked questions'
    return render_template('site/faq.html', page_title=title)


@blueprint.route('/prices')
def prices():
    title = 'Specials and promotions of laser treatment'
    return render_template('site/prices.html', page_title=title)


@blueprint.route('/blogs_tips')
def blogs_tips():
    title = 'Read our news and tips to make you look gorgeous!'
    return render_template('site/blogs_tips.html', page_title=title)

webapp/user/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from webapp.db import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from flask_login import current_user, login_user, logout_user


blueprint = Blueprint('user', __name__, url_prefix='/user')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('site.index'))
    title = 'Login'
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('you are successfully login')
            return redirect(url_for('site.index'))
        flash('wrong password or login name')
        return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('you are successfully logout')
    return redirect(url_for('site.index'))


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('site.index'))
    title = 'Registration'
    form = RegistrationForm()
    return render_template('user/registration.html', page_title=title, form=form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('You are successfully registered!')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Error in field "{}": {}'.format(getattr(form, field).label.text, error))
        return redirect(url_for('user.register'))

webapp/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ page_title }}</title>
    <meta name="viewport" content="width=device-width">
    <link href="{{ url_for('static', filename='css/reset.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.ico') }}"/>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.1.1.slim.js') }}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/common.js') }}" type="text/javascript"></script>
</head>
<body>
<header>
    {% include "nav.html" %}
</header>
{% block content %}{% endblock %}
<footer>
    <div class="footer">
        <ul>
            <li><a href="/promotions">Promotions</a></li>
            <li><a href="#">Gallery</a></li>
            <li><a href="/blogs_tips">Blogs & Tips</a></li>
            <li><a href="/prices">Prices</a></li>
            <li><a href="/contact">Contact</a></li>
        </ul>
        <hr>

        <div class="footer-content">
            <div class="footer-content-card">
                <div class="footer-logo-badge"></div>
                <h4>LASER RENEW</h4>
                <p>Cell: 063 885 1122<br>
                    Whatsapp: 063 885 1122 <br>
                    Email:laserrenewyou@gmail.com<br>
                    Tre Donne Estate<br>
                    Sir Lowry's Pass<br>
                    Somerset West
                </p>
            </div>

            <div class="footer-map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5942.2302259180815!2d18.908866843584196!3d-34.120441199167985!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1dcdc977d8e70e8d%3A0xe34b5c53cc6ea894!2s7th+Heaven+Lodge-Tre+Donne+Estates!5e0!3m2!1sen!2sza!4v1505314010662"
                        width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div><!--end of footer-content-->

        <div class="copyright">
            <hr>

            <p>Copyright 2017 &copy; www.laserrenewyou.com All Rights Reserved<br>
                Design & Online Marketing by <a href="https://offtrend.co.za/" target="new">Off X Trend</a>
            </p>
        </div>

    </div> <!--end footer-->
</footer>
</body>

webapp/templates/blogs_tips.html
{% extends "base.html" %}
{% block content %}
<header class="header-other">
    {% include "nav.html" %}
    <div class="header-other-logo">
        <img class="logo-img" src="{{ url_for('static', filename='img/spin.png') }}" alt="logo-laser">
    </div>
    <div class="header-other-name">
        <h1>LASER RENEW</h1>
        <hr>
        <h2>Renew You</h2>
    </div>
    <div class="header-other-name">
        <p>Tre Donne Estate,<br> Sir Lowry's Pass, <br>Somerset West</p>
        <p>Cell: 063 885 1122<br> Whatsapp: 063 885 1122 <br>
        </p>
    </div>
</header>
<main>
    <h2>Blogs and Tips</h2>
    <article>
        <h3>
            Definitions and Explanations
        </h3>
        <h4>
            RF (Radio Frequency)
        </h4>
        <p>
            <strong>RF lifting</strong> is a safe procedure that lasts up to 6 months (thereafter touch ups are required
            to be done if necessary). The RF lifting procedure can be done on almost any part of the body, even the head
            (for baldness solutions).<br>
            RF lifting can be done on the following parts of the body; Face; lifting of the cheeks, neck and facial skin
            (this is a non-operational lifting technique option – an alternative to Botox). This treatment noticeably
            removes wrinkles around the eyes, mouth and nose, decreases a double chin and helps with the overall
            formation of a tight facial skin. RF lifting encourages the production of collagen and elastin in your skin.
            The skin’s aging procedure is slowed down which results in less wrinkles appearing over the years. The color
            of your skin is also improved – it becomes bright and radiant. RF lifting can be done both on women and men
            after the age of 35.
        </p>
    </article>
    <article>
        <h4>
            The Calorie Burner Bed
        </h4>
        <p>
            This is a Thermo-Procedure which operates with an infra-red blanket that has become popular due it’s high
            rate of effectiveness. This infra-red blanket works by eliminating your body’s liquids.<br>
            This process will also warm and give relief to painful joints. After each procedure, you can lose up to
            500ml of liquids, which consist of un-needed toxins.
            This treatment also rejuvenates your capillaries which improve your bloods’ circulation, fights cellulite
            and improves your over all look (looking radiant and healthy).<br><br>
            The infra-red beams shine through your skin with a depth of 4cm – reaching the fat layer below. This
            treatment can assist the toning of muscles.
        </p>
        <p>
            <strong>Treatment Length:</strong> 10-15 Treatment Sessions
        </p>
        <p>
            <strong>Recommendations before the treatment:</strong>
            Drink more water to aid the body fluid / toxins removal process.
        </p>
        <p>
            <strong>Contradictions:</strong> The following patients should not consider laser or infra-red
            treatments;<br><br>
            Those who have a blood disease.<br>
            Those who have infections.<br>
            Viruses.<br>
            Swellings.<br>
            Women who are pregnant.<br>
            Women who are currently breast feeding.<br>
            Those who have had a recent operation.
        </p>
    </article>
</main>
{% endblock %}

webapp/templates/contact.html
{% extends "base.html" %}
{% block content %}
    <header class="header-other">
        {% include "nav.html" %}
        <div class="header-other-logo">
            <img class="logo-img" src="{{ url_for('static', filename='img/spin.png') }}" alt="logo-laser">
        </div>
        <div class="header-other-name">
            <h1>LASER RENEW</h1>
            <hr>
            <h2>Renew You</h2>
        </div>
        <div class="header-other-name">
            <p>Tre Donne Estate,<br> Sir Lowry's Pass, <br>Somerset West</p>
            <p>Cell: 063 885 1122<br> Whatsapp: 063 885 1122 <br>
            </p>
        </div>
    </header>
    <main>
        <div class="capsule">
            <div class="main-text">
                <h2>CONTACT</h2>
                <p>Oh, how we love hearing from you! Drop us an e-mail below</p>
            </div>
            <div class="picture">
                <img src="{{ url_for('static', filename='img/contact.jpg') }}" alt="contact">
            </div>
        </div>
        <div class="main-contact-form">
            <form id="contactform">
                <div class="input-div">
                    <input name="name" type="text" placeholder="Name" required size="40" maxlength="100" />
                </div>
                <div class="input-div">
                    <input name="email" type="text" placeholder="Email" required size="40" maxlength="100" />
                </div>
                <div class="input-div">
                    <input name="cell" type="text" placeholder="Phone" required size="40" maxlength="100" />
                </div>
                <div class="texarea-div"><textarea name="text" placeholder="Message" required rows="10" cols="42"></textarea></div>
                <div class="input-div"><button>Send Message</button></div>
            </form>
        </div>
        <hr>
        <div class="telephone">Tel: +27 63 885 1122<br><br>Whatsapp: +27 63 885 1122</div>
        <hr>
        <div class="week-hours">
            <h3>Operating Hours</h3>
            <div class="week-days">
                <div>Monday</div>
                <div>9am - 5pm</div>
            </div>
            <div class="week-days">
                <div>Tuesday</div>
                <div>9am - 5pm</div>
            </div>
            <div class="week-days">
                <div>Wednesday</div>
                <div>9am - 5pm</div>
            </div>
            <div class="week-days">
                <div>Thursday</div>
                <div>9am - 5pm</div>
            </div>
            <div class="week-days">
                <div>Friday</div>
                <div>9am - 5pm</div>
            </div>
            <div class="week-days">
                <div>Saturday</div>
                <div>10am - 1pm</div>
            </div>
            <div class="week-days">
                <div>Sunday </div>
                <div>Closed</div>
            </div>
        </div>
    </main>
{% endblock %}

webapp/templates/faq.html
{% extends "base.html" %}
{% block content %}
<header class="header-other">
    {% include "nav.html" %}
    <div class="header-other-logo">
        <img class="logo-img" src="{{ url_for('static', filename='img/spin.png') }}" alt="logo-laser">
    </div>
    <div class="header-other-name">
        <h1>LASER RENEW</h1>
        <hr>
        <h2>Renew You</h2>
    </div>
    <div class="header-other-name">
        <p>Tre Donne Estate,<br> Sir Lowry's Pass, <br>Somerset West</p>
        <p>Cell: 063 885 1122<br> Whatsapp: 063 885 1122 <br>
        </p>
    </div>
</header>
<main>
    <div class="capsule">
        <div class="main-text">
            <h2>FAQ's</h2>
            <p>Here are some Frequently Asked Questions about using Laser Treatment as well as our calorie burner
                bed:</p>
        </div>
        <div class="picture">
            <img src="{{ url_for('static', filename='img/questions.JPG') }}" alt="questions">
        </div>
    </div>
    <hr>
    <div class="week-hours">
        <h3>Is laser treatment dangerous?</h3>
        <div class="week-days">
            We all have a current method of removing hair, whether it's shaving, plucking or waxing. Waxing, plucking
            and shaving is quick and not expensive, however these options are only temporary solutions. This is why many
            people choose to go with the path of laser hair removal. Frequent physical friction given to the skin
            through shaving and waxing can cause some to experience skin irritations, flaking and sensitivity. Laser
            treatment treats the skin with a lot more care. Laser therapy uses an intense bean of light to remove hair
            through a process which is known as photothermolysis. The heat of the laser is absorbed by the hair root
            causing the follicle to corrupt. This stops future hair growth. The darker your hair, the more light is
            absorbed, which means - the more effective the hair removal will be. In general, laser hair removal is known
            not to be as effective for those with white or grey hair as very little light is absorbed. All other
            treatments work in a similar way. The risks of using laser treatment involve temporary potential damage to
            the skin that surrounds hair follicles. Common symptoms include skin irritation such as redness, swelling or
            mild pain. Sometimes the laser can lighten or darken the skin and in very rare instances the laser can cause
            scarring or blistering. But you really have to be unlucky to experience either of these, and this is why
            it's also important to choose the laser treatment salon that you trust. If you are concerned about the
            possibility of skin damage or if you have ever had issues with scarring, tell the technicians so they can
            adjust the settings on the laser accordingly to minimize the risks.
        </div>

        <h3>What can laser treatment do?</h3>
        <div class="week-days">
            Laser treatments are truly like magicians. With laser treatments you can remove hair semi-permanently (from
            anywhere and everywhere on the body), remove permanent tattoos, remove wrinkles, tighten the skin,
            rejuvenate the skin and act as a breast lift assistant.
        </div>

        <h3>How many sessions do I need to see a result?</h3>
        <div class="week-days">
            Because hair is always growing in different stages and skin cells regenerate, multiple laser treatments are
            often needed. On average, it can take anywhere from four to eight treatments to fully see the result. Some
            lucky individuals see a result after one session! Although laser hair removal is touted as a permanent
            option, it is not guaranteed, and you may need occasional touch-up treatments. There are thousands of people
            all around the world who have made use of laser therapy for various treatments and have been left absolutely
            happy!
        </div>

        <h3>Is the treatment painful?</h3>
        <div class="week-days">
            The degree of pain that you feel during a treatment will depend on the type of treatment you have chosen and
            the amount of treatment you undergo. In many cases, the degree of pain that is felt is compared to a rubber
            band snapping against your skin. During laser treatment, a topical anesthesia is sometimes applied with
            sedation, especially when treating specific areas of the face. You will be awake yet relaxed, feeling
            minimal discomfort. Other laser skin procedures can be pain-free for some patients, while others experience
            varying degrees of light discomfort. Much of this depends on the sensitivity of your skin itself.
        </div>

        <h3>How often can I have laser treatment sessions?</h3>
        <div class="week-days">
            Traditionally, having your treatments 4-6 weeks apart is ideal - this gives the treatment a higher chance of
            reaching all of the skin cells / hair follicles.
        </div>

        <h3>Is laser treatment permanent?</h3>
        <div class="week-days">
            Our machine removes hair permanently. This means that you might have to return for touch up's every 6-8
            months (depending on your hair growth, your hair might not even grow back at all). Our bodies are not like
            machines, they are so delicate - therefore there is no rule-book to how your hair follicles will regenerate
            (if they even will at all).
        </div>

    </div>
</main>
{% endblock %}

webapp/templates/header.html
<header class="header-other">
    {% include "nav.html" %}
    <div class="header-other-logo">
        <img class="logo-img" src="{{ url_for('static', filename='img/spin.png') }}" alt="logo-laser">
    </div>
    <div class="header-other-name">
        <h1>LASER RENEW</h1>
        <hr>
        <h2>Renew You</h2>
    </div>
    <div class="header-other-name">
        <p>Tre Donne Estate,<br> Sir Lowry's Pass, <br>Somerset West</p>
        <p>Cell: 063 885 1122<br> Whatsapp: 063 885 1122 <br>
        </p>
    </div>
</header>

webapp/templates/index.html
{% extends "base.html" %}
{% block content %}
<header>
    {% include "nav.html" %}
</header>
<div class="sect-one">
    <div class="logo">
        <img class="logo-img" src="{{ url_for('static', filename='img/spin.png') }}" alt="logo-laser">
    </div>
    <div class="name">
        <h1>LASER RENEW</h1>
        <hr>
        <h2>Renew You</h2>
        <h3>"Loving yourself is the greatest Revolution"</h3>
    </div>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert-login" role="alert">
            {% for message in messages %}
                {{ message }}<br>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
</div> <!--end of sect-one-->
<div class="subsect">
    <div class="picture"><img src="{{ url_for('static', filename='img/welcome.jpg') }}" alt="welcome"></div>
    <div class="text">
        <p>Hello! Welcome to the Laser Renew website - the first step to achieving your smooth beauty goals!</p>
        <p>We are a small (great things come in small packages) private salon situated on Sir Lowry's Pass road in
            Somerset West, run by Tatiana Semenova. We offer a range of laser treatments as well as a calorie burner bed
            at impressive rates, gentle care, marvelous professionalism and warm company!</p>
    </div>
</div> <!--end susect-->
<div class="sect-two"></div>
<div class="subsect">
    <div class="picture"><img src="{{ url_for('static', filename='img/treatment.jpg') }}" alt="treatment"></div>
    <div class="text">
        <p>Our machines have been imported from Europe, the latest, finest and most trusted equipment in the beauty
            industry. So whether you are looking for semi-permanent hair removal solutions, wrinkle removal, tattoo
            removal, skin tightening, skin rejuvenation or you're looking for a simple way to burn extra calories - you
            have come to the right place!
            Booking a session with us is not only going to result in you checking-off an item on your beauty to-do list,
            but it is a relaxation treat - exactly what one needs during a busy week. Soothing music, scented air with
            natural oil's and ... peace and quiet. Doesn't that sound like bliss?</p>
    </div>
</div>
<div class="sect-three"></div>
{% endblock %}

webapp/templates/login.html
{% extends "base.html" %}
{% block content %}
<main>
    <h1>{{ page_title }}</h1>
    <div class="main-contact-form">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert-login" role="alert">
            {% for message in messages %}
                {{ message }}<br>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
        <form id="contact-form" action="{{ url_for('process_login') }}" method="post">
            {{ form.hidden_tag() }}
            <div class="input-div">
                <input name="username" type="text" placeholder="User name" required size="40" maxlength="100"/>
            </div>
            <div class="input-div">
                <input name="password" type="password" placeholder="password" required size="40" maxlength="100"/>
            </div>
            <div class="input-div">
                <button type="submit">login</button>
            </div>
        </form>
    </div>
</main>
{% endblock %}

webapp/templates/nav.html
    <nav class="header-nav">
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/promotions">Promotions</a></li>
            <li><a href="/faq">FAQ</a></li>
            <li><a href="/prices">Prices</a></li>
            <li><a href="/contact">Contact</a></li>
        </ul>
        <ul>
            {% if current_user.is_authenticated %}
            <li>"Hello {{ current_user.username }}"</li>
                {% if current_user.is_admin %}
            <li><a href="{{ url_for('admin.admin_index') }}">Admin</a></li>
                {% endif %}
            <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
            {% else %}
            <li><a href="{{ url_for('user.login') }}">Login</a></li>
            <li><a href="{{ url_for('user.register') }}">Register</a></li>
            {% endif %}
        </ul>
    </nav>

webapp/templates/promotions.html
{% extends "base.html" %}
{% block content %}
<header class="header-other">
    {% include "nav.html" %}
    <div class="header-other-logo">
        <img class="logo-img" src="{{ url_for('static', filename='img/spin.png') }}" alt="logo-laser">
    </div>
    <div class="header-other-name">
        <h1>LASER RENEW</h1>
        <hr>
        <h2>Renew You</h2>
    </div>
    <div class="header-other-name">
        <p>Tre Donne Estate,<br> Sir Lowry's Pass, <br>Somerset West</p>
        <p>Cell: 063 885 1122<br> Whatsapp: 063 885 1122 <br>
        </p>
    </div>
</header>
<main>
    <div class="capsule">
        <div class="main-text">
            <h2>WINTER SPECIAL!</h2>
            <p>Book a 30 min Laser Renew session and receive a free 30 min sauna blanket treatment!</p>
        </div>
        <div class="picture">
            <img src="{{ url_for('static', filename='img/winner.jpg') }}" alt="winning">
        </div>
    </div>
    <hr>
</main>
{% endblock %}

webapp/templates/site/promotions.html
{% extends "base.html" %}
{% block content %}
{% include "header.html" %}
<main>
    <div class="capsule">
        <div class="main-text">
            <h2>WINTER SPECIAL!</h2>
            <p>Book a 30 min Laser Renew session and receive a free 30 min sauna blanket treatment!</p>
        </div>
        <div class="picture">
            <img src="{{ url_for('static', filename='img/winner.jpg') }}" alt="winning">
        </div>
    </div>
    <hr>
</main>
{% endblock %}

webapp/templates/user/login.html
{% extends "base.html" %}
{% block content %}
<main>
    <h1>{{ page_title }}</h1>
    <div class="main-contact-form">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert-login" role="alert">
            {% for message in messages %}
                {{ message }}<br>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
        <form id="contact-form" action="{{ url_for('user.process_login') }}" method="post">
            {{ form.hidden_tag() }}
            <div class="input-div">
                <input name="username" type="text" placeholder="User name" required size="40" maxlength="100"/>
            </div>
            <div class="input-div">
                <input name="password" type="password" placeholder="password" required size="40" maxlength="100"/>
            </div>
            <div class="input-div form-check-box">
                {{ form.remember_me(class_='form-check-tick') }}
                {{ form.remember_me.label(class_='form-check-label') }}
            </div>
            <div class="input-div last">
                <button type="submit">login</button>
            </div>
        </form>
    </div>
    <div class="blank"></div>
</main>
{% endblock %}

webapp/templates/user/registration.html
{% extends "base.html" %}
{% block content %}
<main>
    <div class="blank"></div>
    <h1>{{ page_title }}</h1>
    <div class="main-contact-form">
        <div class="alert-login">
            {% with messages = get_flashed_messages() %}
              {% if messages %}
                {% for message in messages %}
                <div class="danger" role="alert">
                        {{ message }}<br>
                </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
        </div>
        <form id="contact-form" action="{{ url_for('user.process_reg') }}" method="post">
            {{ form.hidden_tag() }}
            <div class="input-div">
                <input name="username" type="text" placeholder="User name" required size="40" maxlength="100"/>
            </div>
            <div class="input-div">
                <input name="email" type="text" placeholder="Email" required size="40" maxlength="100"/>
            </div>
            <div class="input-div">
                <input name="password" type="password" placeholder="password" required size="40" maxlength="100"/>
            </div>
            <div class="input-div">
                <input name="password2" type="password2" placeholder="Repeat password" required size="40" maxlength="100"/>
            </div>
            <div class="input-div last">
                <button type="submit">register</button>
            </div>
        </form>
    </div>
    <div class="blank"></div>
</main>
{% endblock %}